# Forwardpropagation


## Simple Network

In [23]:
def relu(z):
    return max(0, z)

def feed_forward(x, Wh, Wo): # x is input, Wo and Wh are the weights 
    # Hidden layer
    Zh = x * Wh
    H = relu(Zh)
    
    # Output Layer
    Zo = H * Wo
    output = relu(Zo)
    return output
# Zo, Zh are weighted inputs



## Larger Network

### Forward Propagation using Matrics

In [55]:
import numpy as np

# Assuming these are global variables
input_layer_size = 1
hidden_layer_size = 2
output_layer_size = 2

# Initialize weights
def init_weights():
    Wh = np.random.randn(input_layer_size, hidden_layer_size) * np.sqrt(2.0 / input_layer_size)
    Wo = np.random.randn(hidden_layer_size, output_layer_size) * np.sqrt(2.0 / hidden_layer_size)
    return Wh, Wo

# Initialize biases
def init_bias():
    Bh = np.full((1, hidden_layer_size), 0.1)
    Bo = np.full((1, output_layer_size), 0.1)
    return Bh, Bo

# Rectified Linear Unit (ReLU) activation function
def relu(Z):
    return np.maximum(0, Z)

# Derivative of ReLU activation function
def relu_prime(Z):
    return np.where(Z > 0, 1, 0)

# Cost function
def cost(yHat, y):
    cost = np.sum((yHat - y)**2) / 2.0
    return cost

# Derivative of the cost function
def cost_prime(yHat, y):
    return yHat - y

# Feed-forward function
def feed_forward(X, Wh, Wo, Bh, Bo):
    # Hidden layer
    Zh = np.dot(X, Wh) + Bh
    H = relu(Zh)

    # Output layer
    Zo = np.dot(H, Wo) + Bo
    yHat = relu(Zo)

    return H, yHat

# Example usage
# Assuming X, Wh, Wo, Bh, Bo are defined elsewhere
X = np.array([[0.5]])  # Example input
Wh, Wo = init_weights()
Bh, Bo = init_bias()

# Forward propagation
H, yHat = feed_forward(X, Wh, Wo, Bh, Bo)


In [56]:
print(f"X is: \n{X}, \n---------------------------\nWh is: \n{Wh}, \n---------------------------\nWo is: \n{Wo}, \n---------------------------\nBh is: \n{Bh}, \n---------------------------\nBo is: \n{Bo}, \n---------------------------\nH is: \n{H}, \n---------------------------\nyHat is: \n{yHat}")


X is: 
[[0.5]], 
---------------------------
Wh is: 
[[-0.43906806  0.98876226]], 
---------------------------
Wo is: 
[[ 0.40290274 -0.07607934]
 [ 0.13834571  1.8456222 ]], 
---------------------------
Bh is: 
[[0.1 0.1]], 
---------------------------
Bo is: 
[[0.1 0.1]], 
---------------------------
H is: 
[[0.         0.59438113]], 
---------------------------
yHat is: 
[[0.18223008 1.19700301]]


In [41]:
import numpy as np

# Assuming these are global variables
input_layer_size = 3
hidden_layer_size = 4
output_layer_size = 4

# Initialize weights
def init_weights():
    Wh = np.random.randn(input_layer_size, hidden_layer_size) * np.sqrt(2.0 / input_layer_size)
    Wo = np.random.randn(hidden_layer_size, output_layer_size) * np.sqrt(2.0 / hidden_layer_size)
    return Wh, Wo

# Initialize biases
def init_bias():
    Bh = np.full((1, hidden_layer_size), 0.1)
    Bo = np.full((1, output_layer_size), 0.1)
    return Bh, Bo

# Rectified Linear Unit (ReLU) activation function
def relu(Z):
    return np.maximum(0, Z)

# Derivative of ReLU activation function
def relu_prime(Z):
    return np.where(Z > 0, 1, 0)

# Cost function
def cost(yHat, y):
    cost = np.sum((yHat - y)**2) / 2.0
    return cost

# Derivative of the cost function
def cost_prime(yHat, y):
    return yHat - y

# Feed-forward function
def feed_forward(X, Wh, Wo, Bh, Bo):
    # Hidden layer
    Zh = np.dot(X, Wh) + Bh
    H = relu(Zh)

    # Output layer
    Zo = np.dot(H, Wo) + Bo
    yHat = relu(Zo)

    return H, yHat

# Example usage
# Assuming X, Wh, Wo, Bh, Bo are defined elsewhere
X = np.array([[0.5, 0.3, 0.8], [0.2, 0.6, 0.4], [0.9, 0.7, 0.1]])  # Example input
Wh, Wo = init_weights()
Bh, Bo = init_bias()

# Forward propagation
H, yHat = feed_forward(X, Wh, Wo, Bh, Bo)


In [52]:
print(f"X is: {X}, \nWh is: {Wh}, \nWo is: {Wo}, \nBh is: {Bh}, \nBo is: {Bo}, \nH is: {H}, \nyHat is: {yHat}")


X is: [[0.5 0.3 0.8]
 [0.2 0.6 0.4]
 [0.9 0.7 0.1]], 
Wh is: [[ 0.31587818 -0.25818274  0.03040965 -0.79402227]
 [-0.45223989  0.54254607 -0.94926339 -1.02267271]
 [-1.52788193 -0.8986863   0.11352556 -0.13420148]], 
Wo is: [[ 0.52857265 -0.653141    0.76098277 -0.29458519]
 [ 0.80959597  0.28340164  0.77208731 -0.72443471]
 [ 0.2639299  -0.03547008 -0.09260887  0.13536909]
 [ 0.10362714  0.36392503  0.20522867  0.95556143]], 
Bh is: [[0.1 0.1 0.1 0.1]], 
Bo is: [[0.1 0.1 0.1 0.1]], 
H is: [[0.         0.         0.         0.        ]
 [0.         0.01441658 0.         0.        ]
 [0.         0.15754916 0.         0.        ]], 
yHat is: [[0.1        0.1        0.1        0.1       ]
 [0.1116716  0.10408568 0.11113086 0.08955613]
 [0.22755116 0.14464969 0.2216417  0.        ]]


In [53]:
print(f"X is: \n{X}, \n---------------------------\nWh is: \n{Wh}, \n---------------------------\nWo is: \n{Wo}, \n---------------------------\nBh is: \n{Bh}, \n---------------------------\nBo is: \n{Bo}, \n---------------------------\nH is: \n{H}, \n---------------------------\nyHat is: \n{yHat}")


X is: 
[[0.5 0.3 0.8]
 [0.2 0.6 0.4]
 [0.9 0.7 0.1]], 
---------------------------
Wh is: 
[[ 0.31587818 -0.25818274  0.03040965 -0.79402227]
 [-0.45223989  0.54254607 -0.94926339 -1.02267271]
 [-1.52788193 -0.8986863   0.11352556 -0.13420148]], 
---------------------------
Wo is: 
[[ 0.52857265 -0.653141    0.76098277 -0.29458519]
 [ 0.80959597  0.28340164  0.77208731 -0.72443471]
 [ 0.2639299  -0.03547008 -0.09260887  0.13536909]
 [ 0.10362714  0.36392503  0.20522867  0.95556143]], 
---------------------------
Bh is: 
[[0.1 0.1 0.1 0.1]], 
---------------------------
Bo is: 
[[0.1 0.1 0.1 0.1]], 
---------------------------
H is: 
[[0.         0.         0.         0.        ]
 [0.         0.01441658 0.         0.        ]
 [0.         0.15754916 0.         0.        ]], 
---------------------------
yHat is: 
[[0.1        0.1        0.1        0.1       ]
 [0.1116716  0.10408568 0.11113086 0.08955613]
 [0.22755116 0.14464969 0.2216417  0.        ]]


### Forward Propagation using Tensor

In [57]:
import torch

# Assuming these are global variables
input_layer_size = 1
hidden_layer_size = 2
output_layer_size = 2

# Initialize weights
def init_weights():
    Wh = torch.randn((input_layer_size, hidden_layer_size)) * torch.sqrt(torch.tensor(2.0 / input_layer_size))
    Wo = torch.randn((hidden_layer_size, output_layer_size)) * torch.sqrt(torch.tensor(2.0 / hidden_layer_size))
    return Wh, Wo

# Initialize biases
def init_bias():
    Bh = torch.full((1, hidden_layer_size), 0.1)
    Bo = torch.full((1, output_layer_size), 0.1)
    return Bh, Bo

# Rectified Linear Unit (ReLU) activation function
def relu(Z):
    return torch.maximum(torch.tensor(0.0), Z)

# Derivative of ReLU activation function
def relu_prime(Z):
    return torch.where(Z > 0, torch.tensor(1.0), torch.tensor(0.0))

# Cost function
def cost(yHat, y):
    cost = torch.sum((yHat - y)**2) / 2.0
    return cost

# Derivative of the cost function
def cost_prime(yHat, y):
    return yHat - y

# Feed-forward function
def feed_forward(X, Wh, Wo, Bh, Bo):
    # Hidden layer
    Zh = torch.matmul(X, Wh) + Bh
    H = relu(Zh)

    # Output layer
    Zo = torch.matmul(H, Wo) + Bo
    yHat = relu(Zo)

    return H, yHat

# Example usage
# Assuming X, Wh, Wo, Bh, Bo are defined elsewhere
X = torch.tensor([[0.5]])  # Example input
Wh, Wo = init_weights()
Bh, Bo = init_bias()

# Forward propagation
H, yHat = feed_forward(X, Wh, Wo, Bh, Bo)


In [58]:
print(f"X is: \n{X}, \n---------------------------\nWh is: \n{Wh}, \n---------------------------\nWo is: \n{Wo}, \n---------------------------\nBh is: \n{Bh}, \n---------------------------\nBo is: \n{Bo}, \n---------------------------\nH is: \n{H}, \n---------------------------\nyHat is: \n{yHat}")


X is: 
tensor([[0.5000]]), 
---------------------------
Wh is: 
tensor([[-5.0833,  0.0271]]), 
---------------------------
Wo is: 
tensor([[ 0.1052,  0.9603],
        [-0.5672, -0.5706]]), 
---------------------------
Bh is: 
tensor([[0.1000, 0.1000]]), 
---------------------------
Bo is: 
tensor([[0.1000, 0.1000]]), 
---------------------------
H is: 
tensor([[0.0000, 0.1135]]), 
---------------------------
yHat is: 
tensor([[0.0356, 0.0352]])


In [59]:
import numpy as np

# Assuming these are global variables
input_layer_size = 7
hidden_layer_size = 2
output_layer_size = 3

# Initialize weights
def init_weights():
    Wh = np.random.randn(input_layer_size, hidden_layer_size) * np.sqrt(2.0 / input_layer_size)
    Wo = np.random.randn(hidden_layer_size, output_layer_size) * np.sqrt(2.0 / hidden_layer_size)
    return Wh, Wo

# Initialize biases
def init_bias():
    Bh = np.full((1, hidden_layer_size), 0.1)
    Bo = np.full((1, output_layer_size), 0.1)
    return Bh, Bo

# Rectified Linear Unit (ReLU) activation function
def relu(Z):
    return np.maximum(0, Z)

# Derivative of ReLU activation function
def relu_prime(Z):
    return np.where(Z > 0, 1, 0)

# Cost function
def cost(yHat, y):
    cost = np.sum((yHat - y)**2) / 2.0
    return cost

# Derivative of the cost function
def cost_prime(yHat, y):
    return yHat - y

# Feed-forward function
def feed_forward(X, Wh, Wo, Bh, Bo):
    # Hidden layer
    Zh = np.dot(X, Wh) + Bh
    H = relu(Zh)

    # Output layer
    Zo = np.dot(H, Wo) + Bo
    yHat = relu(Zo)

    return H, yHat

# Example usage
# Assuming X, Wh, Wo, Bh, Bo are defined elsewhere
X = np.random.rand(3, 7)  # Example input with shape (3, 7)
Wh, Wo = init_weights()
Bh, Bo = init_bias()

# Forward propagation
H, yHat = feed_forward(X, Wh, Wo, Bh, Bo)


In [60]:
print(f"X is: \n{X}, \n---------------------------\nWh is: \n{Wh}, \n---------------------------\nWo is: \n{Wo}, \n---------------------------\nBh is: \n{Bh}, \n---------------------------\nBo is: \n{Bo}, \n---------------------------\nH is: \n{H}, \n---------------------------\nyHat is: \n{yHat}")


X is: 
[[0.1777758  0.32407224 0.82789431 0.45242461 0.87796545 0.44541373
  0.12203174]
 [0.99034538 0.27100939 0.74512405 0.7675335  0.06617525 0.74794331
  0.63784326]
 [0.76069864 0.22628498 0.29115476 0.6702625  0.99887712 0.38933085
  0.66647667]], 
---------------------------
Wh is: 
[[-0.21982138  0.03439118]
 [ 1.21924542  0.26754045]
 [ 0.12780842 -0.5648273 ]
 [ 0.12250311  0.3630914 ]
 [-0.09093704 -0.21023998]
 [ 0.28542754  0.11063185]
 [-1.05353683 -0.0825075 ]], 
---------------------------
Wo is: 
[[ 1.22944887  0.35692698  0.13156565]
 [ 0.60225852 -1.02028067 -0.89016526]], 
---------------------------
Bh is: 
[[0.1 0.1]], 
---------------------------
Bo is: 
[[0.1 0.1 0.1]], 
---------------------------
H is: 
[[0.53600879 0.        ]
 [0.         0.08059035]
 [0.         0.04369528]], 
---------------------------
yHat is: 
[[0.7589954  0.291316   0.17052034]
 [0.14853622 0.01777523 0.02826127]
 [0.12631585 0.05541855 0.06110398]]
